//get http://localhost:8080/search?searchTerm=laptop

//get http://localhost:8080/search/TUSB217AIRWBR/details

//get http://localhost:8080/history

//get http://localhost:8080/history?searchTerm=laptop